services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092"
    environment:
      DOCKER_API_VERSION: 1.22
      KAFKA_ADVERTISED_HOST_NAME: 10.212.0.140
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  spark:
    image: jupyter/pyspark-notebook
    ports:
      - "8889:8888"
    volumes:
      - /home/rami/Desktop/docs/pyspark_vol:/home/jovyan/work:rw
    user: root
    environment:
      GRANT_SUDO: 1
  server:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144

  client:
    image: yandex/clickhouse-client
    command: ['--host', 'server']

